### PR TITLE
Stop building the master branch so we get some benefit from the build…

### PR DESCRIPTION
**Pull request by nomis52**
…bots.

### CODE REVIEW

**Comment by peternewman** [comment]
What's the benefit? Don't we just risk putting off any bugs in master so we have a big chunk of work at release time, and lots of challenges to bisect it all?

**Comment by nomis52** [comment]
Well right now the bots are useless, so anything is better than nothing.

**Comment by peternewman** [comment]
Useless why?

**Comment by nomis52** [comment]
They keep failing, we can't release because we have no idea if the 0.9 branch is good.

**Pull request merged**
